CREATE VIEW 
	T13_RefSupplier
AS 
	SELECT
		CATALOGU.GCA_TIERS AS Supplier_code,
		CATALOGU.GCA_ARTICLE AS Internal_reference,
		CATALOGU.GCA_REFERENCE AS Supplier_reference,
		ARTICLE.GA_FAMILLENIV2 AS Family_code,
		CATALOGU.GCA_QUALIFUNITEACH AS Purchasing_unit,
		YTARIFS.YTS_PRIXNET AS Purchasing_price,
		TIERS.T_DEVISE AS Purchasing_currency,
		CATALOGU.GCA_BOOLLIBRE2 AS Consigned,
		CATALOGU.GCA_QECOACH AS Eco_order_qty,
		CATALOGU.GCA_QPCBACH AS Pack_order_qty,
		CATALOGU.GCA_QECOACH AS Min_order_qty,
		'' AS Min_order_value,
		CATALOGU.GCA_DELAILIVRAISON AS Leadtime_days
	FROM 
		[TEST_AVO].[dbo].[CATALOGU]
			INNER JOIN [TEST_AVO].[dbo].[ARTICLE]
				ON
				ARTICLE.GA_ARTICLE = CATALOGU.GCA_ARTICLE
			INNER JOIN [TEST_AVO].[dbo].[TIERS]
				ON
				CATALOGU.GCA_TIERS = TIERS.T_TIERS
			LEFT JOIN [TEST_AVO].[dbo].[YTARIFS]
				ON
					CATALOGU.GCA_ARTICLE = YTARIFS.YTS_ARTICLE
					AND CATALOGU.GCA_TIERS = YTARIFS.YTS_TIERS
			LEFT JOIN [TEST_AVO].[dbo].[LIGNE]
				ON 
				LIGNE.GL_TIERSLIVRE = TIERS.T_TIERS
	WHERE
		GL_NATUREPIECEG = 'BLF' 



				
;
